### PR TITLE
Facebook Login

### PR DESCRIPTION
**Pull request by JCot**
Logging into Facebook works. When you first access the site a pop up shows prompting you to log in. It is possible to just close it without logging in for now.

### CODE REVIEW

**Comment by thenaterhood** [comment]
I think there may be a dependency missing here. In order to run this I needed to install react-tap-event-plugin.

**Comment by JCot** [comment]
I don't think I installed anything extra. Should just have to run npm install if you're missing something.

**Comment by thenaterhood** [comment]
Hmm. May not be this pull, but something in our dependencies may have changed. Something to look into but as long as it works somewhere then whatever. @ethanjurman might have more to say.

**Comment by thenaterhood** [comment]
This looks fine to me, let's get this merged and pushed to our server. @mlw6607 @ethanjurman @CShapleigh

**Comment by evajurman** [comment]
:+1:

**Pull request merged**
